name: slack-avatar

on:
  push:
    branches:
    - master

jobs:
  update-avatar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update avatar on Slack
        run: npm start
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STATE_FILE: state.txt

      - name: Commit avatar state
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add state.txt
            git commit -m "New avatar state"
            git push -f origin state
          fi
